akka {
  logLevel = "INFO"
}

http {
  interface = ${HTTP_INTERFACE}
  port      = ${HTTP_PORT}
}

db {
  url             = ${DB_URL}
  username        = ${DB_USERNAME}
  password        = ${DB_PASSWORD}
  driver          = "org.postgresql.Driver"
  max_pool_size   = 10,
  migration_path  = "classpath:db/migration"
}

oidc {
  issuer = ${OIDC_ISSUER}

  # TODO Должно заполняться из issuer.well-known/openid-configuration
  authorization_endpoint = "http://localhost:9090/oauth2/authorize"
  token_endpoint         = "http://localhost:9090/oauth2/token"
  jwks_uri               = "http://localhost:9090/oauth2/jwks"
  userinfo_endpoint      = "http://localhost:9090/userinfo"
  end_session_endpoint   = "http://localhost:9090/connect/logout"

  client_id     = ${OIDC_CLIENT_ID}
  client_secret = ${OIDC_CLIENT_SECRET}
  redirect_uri  = ${OIDC_REDIRECT_URI}
  scopes        = ["openid"]
}